import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Card from "../src/components/Card/Card";
import FeatureHome from "../src/components/FeatureHome/FeatureHome";
import HeroHome from "../src/components/HeroHome/HeroHome";

const Container = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  width: 70%;
  margin: 0 auto;
  grid-gap: 20px;
  margin-top: 30px;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroHome />
      <Container>
        <Card path="/c1.jpg" title="SERIE 10 FOR OFFICE" />
        <Card path="/c2.jpg" title="LAUNCHING PROMO" />
        <Card path="/c3.jpg" title="SERIE 10 FOR ALL" />
      </Container>
      <FeatureHome />
    </>
  );
};

export default Home;
